# SPDX-License-Identifier: MIT
# Copyright (c) 2026 The Ergon developers

[workspace]
members = [
    "abc-rust-error",
    "abc-rust-lint",
    "bitcoinsuite-core",
    "bitcoinsuite-slp",
    "chronik-db",
    "chronik-observer",
    "chronik-plugin",
    "chronik-plugin-common",
    "chronik-plugin-impl",
    "chronik-proto",
    "chronik-util",
]
default-members = [
    "bitcoinsuite-core",
    "bitcoinsuite-slp",
    "chronik-db",
    "chronik-proto",
]
exclude = [
    "chronik-bridge",
    "chronik-http",
    "chronik-indexer",
    "chronik-lib",
]
resolver = "2"

[workspace.package]
rust-version = "1.85.0"
